version: 0.0.0
jobs:
  build:
    docker:
      - image: python:3.8  # Use the desired Python version

    steps:
      - checkout  # Checkout your code

      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt  # Install your project's dependencies
            pip install pytest  # Install pytest

      - run:
          name: Run Tests
          command: pytest