version: 2.1

################# ORB #################
orbs:
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@2.1.1

################# Arguments to the pip install #################
pip_install_block: &pip_install_block
  pkg-manager: pip
  args: .

################# Command to run tests #################
run_tests_cmd: &run_tests_cmd
  command: |
    cd test/test_scripts
    TESTCLASSES=$(circleci tests glob "test*.py" | sed -e 's/.py//' | circleci tests split)
    python -m unittest $TESTCLASSES -v

################# WORKFLOWS #################
workflows:
  build_and_test:
    jobs:
      - build-and-code-check
      - run-tests
      # - publish_to_pypi
  deploy:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/  # This regular expression matches version tags (e.g., v1.0.0)

################# JOBS #################
jobs:
  # Build the repo and check the code using pyflakes and pylint
  build-and-code-check:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - python/install-packages:
          <<: *pip_install_block
  run-tests:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - python/install-packages:
          <<: *pip_install_block
      - run:
          name: run tests in Python 3.9
          command: cd ~/project; python test/run_all_tests.py --no_pyflakes --no_pylint
  publish_to_pypi:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Publish to PyPI
          command: |
            pip install twine
            python setup.py sdist bdist_wheel
            twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
          environment:
            TWINE_USERNAME: $PYPI_USERNAME
            TWINE_PASSWORD: $PYPI_PASSWORD
  deploy:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            # Your deployment commands go here